### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by Tarseus** [smallg0at/StudentSelector#1]
请先改标题
**描述一下bug**
点击“提交”按钮没有提交

**重现过程**
对于任意指令点击“提交“按钮

**应有行为**
得到提交后的反馈

**屏幕截图（如有）**
没有得到响应

**浏览器信息**
？

**Comment by smallg0at** [comment]
你需要点击 提交 文字，周边区域由于未知原因无法点击...

**Comment by smallg0at** [comment]
修完了。
