### ISSUE TITLE
对空格的不正确处理

### ISSUE THREAD

**Issue by MrScottLee** [smallg0at/StudentSelector#10]
请先改标题
**描述一下bug**
含空格的姓名输入不同数量空格会显示相同姓名

**重现过程**
先输入“1 2”
再输入“1  2”
再输入“1   2”
再输入“1    2”
结果显示添加了4个“1 2”
**应有行为**
“1 2”添加成功
“1  2”添加成功
“1   2”添加成功
“1    2”添加成功

**屏幕截图（如有）**
![图片](https://user-images.githubusercontent.com/48752923/55871976-6cdf5400-5bbe-11e9-96ab-f6dfdd82c31d.png)

**浏览器信息**
Firefox 66.0.2 (20190326175229)

**Comment by LYQhh** [comment]
用了一下正则表达式，修好了
