### ISSUE TITLE
初次进入会异常显示"True"

### ISSUE THREAD

**Issue by MrScottLee** [smallg0at/StudentSelector#12]
**描述一下bug**
输入http://211.68.74.233/dm/main.php 进入时浏览器左上角会显示“true”

**重现过程**
输入http://211.68.74.233/dm/main.php
回车进入
![图片](https://user-images.githubusercontent.com/48752923/56277215-83455c80-6136-11e9-87ad-6092170b65b3.png)

**应有行为**
emm

**屏幕截图（如有）**
![图片](https://user-images.githubusercontent.com/48752923/56277236-8c362e00-6136-11e9-9474-feb527c82524.png)

**浏览器信息**
Firefox 66.0.3 (20190409155332)

**Comment by smallg0at** [comment]
我也不知道怎么出现的。。。。我慢慢查一下代码吧

**Comment by LYQhh** [comment]
现在似乎没有了？

**Comment by LYQhh** [comment]
好像确实没了，先把issue关了，要是再出现就再提吧
