### ISSUE TITLE
”随机“指令问题

### ISSUE THREAD

**Issue by Tarseus** [smallg0at/StudentSelector#2]
请先改标题
**描述一下bug**
在列表没有内容时，点击”随机“->”提交“后报错

**重现过程**
依次点击”随机“->”提交“按钮

**应有行为**
提示”列表没有内容“或其他什么的...

**屏幕截图（如有）**

**浏览器信息**

**Comment by smallg0at** [comment]
已知bug，我去修一下

**Comment by smallg0at** [comment]
修完了。
