### ISSUE TITLE
关于能成功提交空格且提交后显示的表格删除按键错位的问题

### ISSUE THREAD

**Issue by LYQhh** [smallg0at/StudentSelector#3]
**描述一下bug**
如题

**重现过程**
提交由任意长度的空格组成的字符串

**应有行为**
返回内容不能为空并阻止提交

**屏幕截图（如有）**
![image](https://user-images.githubusercontent.com/48676289/55467388-c3371a80-5633-11e9-8c8e-533f541b3e4d.png)

**浏览器信息**
Chrome浏览器

**Comment by smallg0at** [comment]
Fixed.
