### ISSUE TITLE
关于UI界面的建议

### ISSUE THREAD

**Issue by LYQhh** [smallg0at/StudentSelector#4]
![image](https://user-images.githubusercontent.com/48676289/55468080-3725f280-5635-11e9-8724-1cf60254a1da.png)

如图，在第一次添加了一个人名后使用这个界面时，我一度以为右上角的的随机选择按钮的功能是移动界面用的，然后也不明白那个红色按钮是干啥的。希望能加上文字提示或是其它醒目的标志。

**Comment by smallg0at** [comment]
收到。
麻烦在这里：[https://material.io/tools/icons/?style=baseline](https://material.io/tools/icons/?style=baseline) 寻找合适的图标建议

**Comment by smallg0at** [comment]
解决了。

**Comment by smallg0at** [comment]
修复来自：cc2696ba70bc614df8174757bd4c76fe2c8bc3cd
