### ISSUE TITLE
无法输入html代码段

### ISSUE THREAD

**Issue by louis18519** [smallg0at/StudentSelector#8]

**Comment by MrScottLee** [comment]
**描述一下bug**
输入HTML代码段会鬼畜

**重现过程**
输入"《p》"
![图片](https://user-images.githubusercontent.com/48752923/55870247-b9c12b80-5bba-11e9-9a1f-e24aea4c304e.png)
输入"《h1》"
![图片](https://user-images.githubusercontent.com/48752923/55870321-e5dcac80-5bba-11e9-8b23-3313158a5d41.png)
输入"《h1》1《h1》"
![图片](https://user-images.githubusercontent.com/48752923/55870476-3d7b1800-5bbb-11e9-8a5a-182e059acabe.png)
输入"《button》"
![图片](https://user-images.githubusercontent.com/48752923/55870591-859a3a80-5bbb-11e9-8c70-534641551f6c.png)
输入"《fieldset》"
![图片](https://user-images.githubusercontent.com/48752923/55870722-c42ff500-5bbb-11e9-9b7d-a73ed0561ce2.png)

**应有行为**
emmm

**屏幕截图（如有）**
见上

**浏览器信息**
Firefox 66.0.2 (20190326175229)

**Comment by maohj** [comment]
用户输入一定要检查，不然会被玩得很惨
