### ISSUE TITLE
画个favicon

### ISSUE THREAD

**Issue by MrScottLee** [smallg0at/StudentSelector#9]
请先改标题
**描述一下bug**
界面技术中心图标出错

**重现过程**
![图片](https://user-images.githubusercontent.com/48752923/55869966-2d166d80-5bba-11e9-9c40-850a8d05eb47.png)

**应有行为**
![微信图片_20181010084727 - 副本](https://user-images.githubusercontent.com/48752923/55870099-6fd84580-5bba-11e9-8be3-c14594a1c3a7.png)

**屏幕截图（如有）**

**浏览器信息**
Firefox 66.0.2 (20190326175229)

**Comment by smallg0at** [comment]
Not bug, changing label
